name: Process data
on:
  push:
    branches:
      - master
    paths:
      - "media/**/*"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  process-card-data:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install AWS CLI
        run: pip install awscli
      - name: Push images to bucket
        shell: bash
        run: ./push.sh
